spring:
    datasource:
        url: "jdbc:h2:mem:testdb"
    application:
        name: "humidity-service" 
server:
    port: 8093


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://register:8761/eureka
  instance:
    hostname: register
    prefer-ip-address: true
eureka.client.enabled: true

