my.unit: "Celsius"

server.port: 8091

spring:
   datasource:
        url: "jdbc:h2:mem:testdb"
  

 


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://register:8761/eureka
  instance:
    hostname: register
    prefer-ip-address: true
eureka.client.enabled: true



management.endpoints.web.exposure.include: "*"